#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <tag>" >&2
  exit 2
fi
TAG="$1"
REPO="${REPO:-${GITHUB_REPOSITORY:-}}"
API="https://api.github.com/repos/$REPO"

echo "Checking for existing release with tag: $TAG"
resp=$(curl -sS -H "Authorization: token $GITHUB_TOKEN" "$API/releases/tags/$TAG" || true)

# If not found, create release
if echo "$resp" | grep -q 'Not Found'; then
  echo "Release not found, creating..."
  create_resp=$(curl -sS -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" \
    -d "{\"tag_name\": \"$TAG\", \"name\": \"$TAG\", \"body\": \"Release $TAG generated by CI\", \"draft\": false, \"prerelease\": false }" \
    "$API/releases")
  upload_url=$(python - <<'PY'
import sys, json
obj = json.load(sys.stdin)
print(obj.get('upload_url',''))
PY
  <<<"$create_resp"
else
  # reuse existing release
  upload_url=$(python - <<'PY'
import sys, json
obj = json.load(sys.stdin)
print(obj.get('upload_url',''))
PY
  <<<"$resp"
fi

if [ -z "$upload_url" ] || [ "$upload_url" = "null" ]; then
  echo "Failed to obtain upload_url for release" >&2
  echo "resp: $resp" >&2
  exit 1
fi

# write to GITHUB_OUTPUT so workflow step outputs can access it
if [ -z "${GITHUB_OUTPUT:-}" ]; then
  echo "GITHUB_OUTPUT not set" >&2
  exit 1
fi

printf "upload_url=%s\n" "$upload_url" >> "$GITHUB_OUTPUT"

echo "Created/using release with upload_url: $upload_url"
