// <auto-generated />
#nullable enable

using System.Globalization;
using System.Resources;

namespace PhotoSorterApp.Resources;

public static class UiStrings
{
    private static readonly ResourceManager ResourceManagerInstance = new("PhotoSorterApp.Resources.UiStrings", typeof(UiStrings).Assembly);
    private static CultureInfo? resourceCulture;

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    private static string GetString(string name) => ResourceManagerInstance.GetString(name, resourceCulture) ?? name;

    public static string PersonsWindow_Title => GetString(nameof(PersonsWindow_Title));
    public static string PersonsWindow_HeaderDescription => GetString(nameof(PersonsWindow_HeaderDescription));
    public static string PersonsWindow_EmptySelectionHint => GetString(nameof(PersonsWindow_EmptySelectionHint));
    public static string PersonsWindow_ButtonBack => GetString(nameof(PersonsWindow_ButtonBack));
    public static string PersonsWindow_ButtonForward => GetString(nameof(PersonsWindow_ButtonForward));
    public static string PersonsWindow_DeleteFaceMenuItem => GetString(nameof(PersonsWindow_DeleteFaceMenuItem));
    public static string PersonsWindow_ButtonRefresh => GetString(nameof(PersonsWindow_ButtonRefresh));
    public static string PersonsWindow_ButtonRename => GetString(nameof(PersonsWindow_ButtonRename));
    public static string PersonsWindow_ButtonMerge => GetString(nameof(PersonsWindow_ButtonMerge));
    public static string PersonsWindow_ButtonDeleteMarkedFaces => GetString(nameof(PersonsWindow_ButtonDeleteMarkedFaces));
    public static string PersonsWindow_ButtonDelete => GetString(nameof(PersonsWindow_ButtonDelete));
    public static string PersonsWindow_ButtonClose => GetString(nameof(PersonsWindow_ButtonClose));
    public static string PersonsWindow_SortByNameAsc => GetString(nameof(PersonsWindow_SortByNameAsc));
    public static string PersonsWindow_SortByNameDesc => GetString(nameof(PersonsWindow_SortByNameDesc));
    public static string PersonsWindow_SortByFaceCountAsc => GetString(nameof(PersonsWindow_SortByFaceCountAsc));
    public static string PersonsWindow_SortByFaceCountDesc => GetString(nameof(PersonsWindow_SortByFaceCountDesc));
    public static string PersonsWindow_PageStatusFormat => GetString(nameof(PersonsWindow_PageStatusFormat));
    public static string PersonsWindow_LoadingFaces => GetString(nameof(PersonsWindow_LoadingFaces));
    public static string PersonsWindow_LoadingFacesProgress => GetString(nameof(PersonsWindow_LoadingFacesProgress));
    public static string PersonsWindow_SelectPersonMessage => GetString(nameof(PersonsWindow_SelectPersonMessage));
    public static string PersonsWindow_SelectSourcePersonMessage => GetString(nameof(PersonsWindow_SelectSourcePersonMessage));
    public static string PersonsWindow_InfoTitle => GetString(nameof(PersonsWindow_InfoTitle));
    public static string PersonsWindow_RenameDialogTitle => GetString(nameof(PersonsWindow_RenameDialogTitle));
    public static string PersonsWindow_MergeDialogPrompt => GetString(nameof(PersonsWindow_MergeDialogPrompt));
    public static string PersonsWindow_DeletePersonConfirm => GetString(nameof(PersonsWindow_DeletePersonConfirm));
    public static string PersonsWindow_DeleteConfirmTitle => GetString(nameof(PersonsWindow_DeleteConfirmTitle));
    public static string PersonsWindow_SelectMarkedFacesMessage => GetString(nameof(PersonsWindow_SelectMarkedFacesMessage));
    public static string PersonsWindow_DeleteMarkedFacesConfirm => GetString(nameof(PersonsWindow_DeleteMarkedFacesConfirm));
    public static string PersonsWindow_DeleteFacesConfirmTitle => GetString(nameof(PersonsWindow_DeleteFacesConfirmTitle));
    public static string PersonsWindow_DeleteSingleFaceConfirm => GetString(nameof(PersonsWindow_DeleteSingleFaceConfirm));
    public static string PersonsWindow_DeleteFaceConfirmTitle => GetString(nameof(PersonsWindow_DeleteFaceConfirmTitle));

    public static string UnknownFacesWindow_Title => GetString(nameof(UnknownFacesWindow_Title));
    public static string UnknownFacesWindow_HeaderDescription => GetString(nameof(UnknownFacesWindow_HeaderDescription));
    public static string UnknownFacesWindow_Loading => GetString(nameof(UnknownFacesWindow_Loading));
    public static string UnknownFacesWindow_FoundSuffix => GetString(nameof(UnknownFacesWindow_FoundSuffix));
    public static string UnknownFacesWindow_ClearSelection => GetString(nameof(UnknownFacesWindow_ClearSelection));
    public static string UnknownFacesWindow_MoveToCluster => GetString(nameof(UnknownFacesWindow_MoveToCluster));
    public static string UnknownFacesWindow_DeleteSelected => GetString(nameof(UnknownFacesWindow_DeleteSelected));
    public static string UnknownFacesWindow_AssignNameToClusters => GetString(nameof(UnknownFacesWindow_AssignNameToClusters));
    public static string UnknownFacesWindow_Close => GetString(nameof(UnknownFacesWindow_Close));
    public static string UnknownFacesWindow_AssignTooltip => GetString(nameof(UnknownFacesWindow_AssignTooltip));
}
